# This file define workflow for github actions.
# Terraform will be applied through github Actions
name: Create Kubernetes Cluster and Install Argo CD
on: push
jobs:
  deploy-terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
    - uses: action/checkout@v3.0.0
    - name: Install Terraform
      id: terraform-install
      run: get -O terraform.zip https://releases.hashicorp.com/terraform/1.1.7/terraform_1.1.7_linux_amd64.zip && unzip terraform.zip && chmod +x terraform && sudo mv terraform /usr/local/bin
    - name: Check Terraform Version
      id: terraform-version
      run: terraform --version